name: Opushire CI/CD

on:
  push:
    branches: [ "master", "soumik" ]
  pull_request:
    branches: [ "master", "soumik" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./opushire

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: './opushire/package-lock.json'
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Build Next.js
      run: npm run build
      env:
        NEXT_PUBLIC_API_URL: http://localhost:5000/api

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./opushire-backend

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: './opushire-backend/package-lock.json'
        
    - name: Install dependencies
      run: npm ci || npm install
      
    - name: Build Express.js App
      run: npm run build
